blueprint:
  name: Cover control with Tradfri open/close remote (Zigbee2MQTT)
  description: |
    Control a cover with an IKEA Tradfri open/close button remote over Zigbee2MQTT

    Short press on ☼ button will open the cover (or stop if already opening).
    Short press on ☰ button will close the cover (or stop if already closing).
    Long press on ☼ or ☰ will stop the cover.

    Inspired by: https://github.com/FriedCheese2006/HomeAssistant/blob/main/Ikea_button_z2m.yaml
  domain: automation
  source_url: https://github.com/FriedCheese2006/HomeAssistant/blob/main/Ikea_button_z2m.yaml
  input:
    remote:
      name: Remote
      description: "IKEA Tradfri open/close remote (E1766)"
      selector:
        device:
          integration: mqtt
          manufacturer: IKEA
    cover:
      name: Cover
      description: The cover to control
      selector:
        entity:
          domain: cover

trigger:
  - platform: device
    domain: mqtt
    device_id: !input remote
    type: action
    subtype: open
    id: open
  - platform: device
    domain: mqtt
    device_id: !input remote
    type: action
    subtype: close
    id: close
  - platform: device
    domain: mqtt
    device_id: !input remote
    type: action
    subtype: stop
    id: stop

action:
  - variables:
      cover_entity: !input cover
  - choose:
      - conditions:
          - condition: trigger
            id: open
        sequence:
          - if:
              - condition: state
                entity_id: !input cover
                state: "opening"
            then:
              - service: cover.stop_cover
                entity_id: !input cover
            else:
              - service: cover.open_cover
                entity_id: !input cover
      - conditions:
          - condition: trigger
            id: close
        sequence:
          - if:
              - condition: state
                entity_id: !input cover
                state: "closing"
            then:
              - service: cover.stop_cover
                entity_id: !input cover
            else:
              - service: cover.close_cover
                entity_id: !input cover
      - conditions:
          - condition: trigger
            id: stop
        sequence:
          - service: cover.stop_cover
            entity_id: !input cover

mode: single
