blueprint:
  name: Cover control with Tradfri open/close remote (Zigbee2MQTT)
  description: |
    Control one or more covers with an IKEA Tradfri open/close button remote over Zigbee2MQTT

    Short press on ☼ button will open the cover(s) (or stop if already opening).
    Short press on ☰ button will close the cover(s) (or stop if already closing).
    Long press on ☼ or ☰ will stop the cover(s).

    Inspired by: https://github.com/FriedCheese2006/HomeAssistant/blob/main/Ikea_button_z2m.yaml
  domain: automation
  source_url: https://github.com/FriedCheese2006/HomeAssistant/blob/main/Ikea_button_z2m.yaml
  input:
    remote:
      name: Remote
      description: "IKEA Tradfri open/close remote (E1766)"
      selector:
        device:
          integration: mqtt
          manufacturer: IKEA
    covers:
      name: Covers
      description: The cover(s) to control
      selector:
        entity:
          domain: cover
          multiple: true

trigger:
  - platform: device
    domain: mqtt
    device_id: !input remote
    type: action
    subtype: open
    id: open
  - platform: device
    domain: mqtt
    device_id: !input remote
    type: action
    subtype: close
    id: close
  - platform: device
    domain: mqtt
    device_id: !input remote
    type: action
    subtype: stop
    id: stop

action:
  - variables:
      covers: !input covers
  - choose:
      - conditions:
          - condition: trigger
            id: open
        sequence:
          - action: cover.open_cover
            target:
              entity_id: "{{ covers }}"
      - conditions:
          - condition: trigger
            id: close
        sequence:
          - action: cover.close_cover
            target:
              entity_id: "{{ covers }}"
      - conditions:
          - condition: trigger
            id: stop
        sequence:
          - action: cover.stop_cover
            target:
              entity_id: "{{ covers }}"

mode: single
