blueprint:
  name: Cover control with Tradfri open/close remote (Zigbee2MQTT)
  description: |
    Control a cover with an IKEA Tradfri open/close button remote over Zigbee2MQTT

    Short press on ☼ button will open the cover (or stop if already opening).
    Short press on ☰ button will close the cover (or stop if already closing).
    Long press on ☼ or ☰ will stop the cover.

    Inspired by: https://github.com/FriedCheese2006/HomeAssistant/blob/main/Ikea_button_z2m.yaml
  domain: automation
  source_url: https://github.com/FriedCheese2006/HomeAssistant/blob/main/Ikea_button_z2m.yaml
  input:
    remote_topic:
      name: Remote MQTT Topic
      description: "The Zigbee2MQTT topic for your remote (e.g., zigbee2mqtt/living_room_switch)"
      selector:
        text:
    cover:
      name: Cover
      description: The cover to control
      selector:
        target:
          entity:
            domain: cover

trigger:
  - platform: mqtt
    topic: !input remote_topic
    value_template: "{{ value_json.action }}"

action:
  - variables:
      command: "{{ trigger.payload }}"
      cover_target: !input cover
  - choose:
      - conditions:
          - "{{ command == 'open' }}"
        sequence:
          - if:
              - condition: template
                value_template: "{{ is_state_attr((cover_target.entity_id | default([cover_target]))[0], 'moving', 'OPENING') or state_attr((cover_target.entity_id | default([cover_target]))[0], 'current_position') | int(-1) != -1 and is_state((cover_target.entity_id | default([cover_target]))[0], 'opening') }}"
            then:
              - service: cover.stop_cover
                target: !input cover
            else:
              - service: cover.open_cover
                target: !input cover
      - conditions:
          - "{{ command == 'close' }}"
        sequence:
          - if:
              - condition: template
                value_template: "{{ is_state_attr((cover_target.entity_id | default([cover_target]))[0], 'moving', 'CLOSING') or state_attr((cover_target.entity_id | default([cover_target]))[0], 'current_position') | int(-1) != -1 and is_state((cover_target.entity_id | default([cover_target]))[0], 'closing') }}"
            then:
              - service: cover.stop_cover
                target: !input cover
            else:
              - service: cover.close_cover
                target: !input cover
      - conditions:
          - "{{ command in ['stop', 'stop_opening', 'stop_closing'] }}"
        sequence:
          - service: cover.stop_cover
            target: !input cover

mode: single
